# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2019, Intel Corporation
#

#
# src/test/obj_many_pools/Makefile -- build obj_many_pools unit test
#
TARGET = obj_many_pools
OBJS = obj_many_pools.o

LIBPMEMOBJ=y

include ../Makefile.inc
