#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/test/pmem2_source_numa/TEST0 -- unittest for getting numa node from source
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem

setup

export PMEM2_LOG_LEVEL=3

# no error
expect_normal_exit ./pmem2_source_numa \
				   $DIR/testfile1 0 \
				   $DIR/testfile2 0 \
				   $DIR/testfile3 1

check

pass
