#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/test/pmem2_source_numa/TEST0 -- unittest for getting numa node from source
#

. ../unittest/unittest.sh

require_test_type medium

require_fs_type pmem

setup

export PMEM2_LOG_LEVEL=2
export PMEM2_LOG_FILE=./test$UNITTEST_NUM.log

# no error
expect_normal_exit ./pmem2_source_numa \
				   $DIR/testfile1 5 0 \
				   $DIR/testfile2 7 0 \
				   $DIR/testfile3 9 0

expect_normal_exit ./util_sds 0 0 \
				   $DIR/testfile1 5 0 \
				   $DIR/testfile2 7 0 \
				   $DIR/testfile3 9 0

grep "shutdown_state_check" test$UNITTEST_NUM.log > grep$UNITTEST_NUM.log || true

check

pass
